# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hamonikr/workspaces/media-downloader/src/logwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logWindow(object):
    def setupUi(self, logWindow):
        logWindow.setObjectName("logWindow")
        logWindow.setWindowModality(QtCore.Qt.WindowModal)
        logWindow.resize(791, 501)
        self.gridLayout = QtWidgets.QGridLayout(logWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.pbClose = QtWidgets.QPushButton(logWindow)
        self.pbClose.setMinimumSize(QtCore.QSize(128, 0))
        self.pbClose.setObjectName("pbClose")
        self.gridLayout.addWidget(self.pbClose, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(logWindow)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 4)
        self.pbClear = QtWidgets.QPushButton(logWindow)
        self.pbClear.setMinimumSize(QtCore.QSize(128, 0))
        self.pbClear.setObjectName("pbClear")
        self.gridLayout.addWidget(self.pbClear, 1, 1, 1, 1)

        self.retranslateUi(logWindow)
        QtCore.QMetaObject.connectSlotsByName(logWindow)

    def retranslateUi(self, logWindow):
        _translate = QtCore.QCoreApplication.translate
        logWindow.setWindowTitle(_translate("logWindow", "Log Window"))
        self.pbClose.setText(_translate("logWindow", "Close"))
        self.pbClear.setText(_translate("logWindow", "Clear"))
